product: ##PRODUCT_NAME##
full_name: ##PRODUCT_NAME_FULL##
type: platform

benchmark_id: ##BENCHMARK_ID##
benchmark_root: "../../linux_os/guide"

profiles_root: "./profiles"

pkg_manager: "apt_get"
init_system: "systemd"

cpes_root: "../../shared/applicability"
cpes:
  # one for each version supported by this product
  - ##PRODUCT_NAME####PRODUCT_VERSION##:
      name: "cpe:/o:##PRODUCT_NAME##:##PRODUCT_VERSION##"
      title: "##PRODUCT_NAME_FULL##"
      check_id: installed_OS_is_##PRODUCT_NAME##